quarkus:
  datasource:
    db-kind: postgresql
    jdbc: false
  index-dependency:
    infrastructure:
      group-id: pl.edu.pw.ee.pz
      artifact-id: infrastructure
    service:
      group-id: pl.edu.pw.ee.pz
      artifact-id: service
    external-service-adapter:
      group-id: pl.edu.pw.ee.pz
      artifact-id: external-service-adapter
  liquibase:
    change-log: db/changelog/changelog.xml
    migrate-at-start: true
mp:
  messaging:
    incoming:
      domain-events-in:
        connector: smallrye-kafka
        topic: domain-events
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        batch: true
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        commit-strategy: ignore
        broadcast: true
        group:
          id: ${quarkus.uuid}
    outgoing:
      domain-events-out:
        connector: smallrye-kafka
        topic: domain-events
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: org.apache.kafka.common.serialization.ByteArraySerializer
domain-events:
  publish-timeout: PT1S
  backoff-timeout: PT0.3S
  max-retries: 3

"%local":
  quarkus:
    http:
      port: 4000
    datasource:
      devservices:
        enabled: false
      db-kind: postgresql
      username: buy_it
      password: buy_it
      reactive:
        url: postgresql://localhost:15432/buy_it
    kafka:
      devservices:
        enabled: false
  kafka:
    bootstrap:
      servers: localhost:19092
  eventstore:
    db:
      hosts:
        - host: "127.0.0.1"
          port: 12111
        - host: "127.0.0.1"
          port: 12112
        - host: "127.0.0.1"
          port: 12113
      username: admin
      password: changeit
      tls: true
  minio:
    client:
      uri: "http://192.168.49.2:31932"
      access-key: "admin"
      secret-key: "changeit"

"%prod":
  quarkus:
    http:
      port: 4000
    datasource:
      devservices:
        enabled: false
      db-kind: postgresql
      username: buy_it
      password: buy_it
      reactive:
        url: postgresql://localhost:15432/buy_it
    kafka:
      devservices:
        enabled: false
  kafka:
    bootstrap:
      servers: localhost:19092
  eventstore:
    db:
      hosts:
        - host: "localhost"
          port: 12111
        - host: "localhost"
          port: 12112
        - host: "localhost"
          port: 12113
      username: admin
      password: changeit
      tls: true
  minio:
    client:
      uri: "http://192.168.49.2:31932"
      access-key: "admin"
      secret-key: "changeit"
